all: 
	gcc storage_server.c storage_server_recieving_request.c storage_server_sending_response.c files_operations/file_delete.c files_operations/file_read.c files_operations/file_information.c   folder_operations/folder_delete.c folder_operations/folder_read.c folder_operations/folder_information.c folder_operations/folder_create.c files_operations/file_create.c -o storage_server

